var bg_bathroom = [{url: "./img/2/01.png"}, {url: "./img/2/02.png", left: -1}];
var bg_hospital_outside = [{url: "./img/3/01.png", timeout: 2}, {url: "./img/3/02.png", timeout: 2}, {url: "./img/3/03.png", timeout: 2}, {url: "./img/3/04.png", timeout: 2, end: true,}];
var bg_hospital_in_on_lower = [{url: "./img/4/put_on/lower-01.png"}, {url: "./img/4/put_on/lower-02.png"}];
var bg_hospital_in_on_raise = [{url: "./img/4/put_on/raise-01.png"}, {url: "./img/4/put_on/raise-02.png", left: 1}];
var bg_hospital_in_on_called = [{url: "./img/4/put_on/called-01.png"}, {url: "./img/4/put_on/called-02.png"}];
var bg_hospital_in_off_lower = [{url: "./img/4/put_off/lower-01.png"}, {url: "./img/4/put_off/lower-02.png"}];
var bg_hospital_in_off_raise = [{url: "./img/4/put_off/raise-01.png"}, {url: "./img/4/put_off/raise-02.png", left: 1}];
var bg_hospital_in_off_called = [{url: "./img/4/put_off/called-01.png"}, {url: "./img/4/put_off/called-02.png"}];
var bg_hospital_in_doctor = [{url: "./img/5/01.png"}, {url: "./img/5/02.png"}];
var bg_hospital_out_discuss = [{url: "./img/6/01.png"}];
var scene = {
	2001:{
		description: "在廁所",
		background: bg_bathroom,
		story_date: "2018/09/30",
		story: ["我懷孕了？！",
		"這不可能...明明做好保護措施了",
		"我怎麼可能懷孕？",
		"我怎麼可能懷孕？",
		"但是驗孕棒上面的確是兩條線，我該怎麼辦？",
		"要不要先跟卓子曜說啊...",
		"他如果知道這件事會有什麼反應？",
		"啊也有可能是驗孕棒不準，還是要再驗一次看看？",],
		btn_left: {
			text: "直接打電話給男友",
			scene: 2002,
		},
		btn_middle: {
			text: "傳 Line 給男友",
			scene: 2003,
		},
		btn_right: {
			text: "再驗一次",
			scene: 2007,
		},
	},
	2002: {
		description: "在廁所-打電話",
		background: bg_bathroom, 
		line: [
		{type: "outgoing dialing", timeout: 1},
		{type: "incoming cancelled", timeout: 5},
		{type: "received", message: "怎麼了？我在補習", timeout: 2},
		{type: "read", message: "我...我好像懷孕了", timeout: 2},
		{type: "received", message: "...", timeout: 3},
		{type: "received", message: "真的假的", timeout: 1},
		{type: "read", message: "我會拿這種事開玩笑嗎", timeout: 3},
		{type: "read", img: "./img/2/03.png", timeout: 3},
		{type: "received", message: "不是拉 我是嚇到了", timeout: 3},
		{type: "received", message: "妳只驗了一次嗎", timeout: 1},
		{type: "read", message: "嗯", timeout: 3},
		{type: "received", message: "你要不要再驗一次啊", timeout: 4},
		{type: "received", message: "不是說有些不太準嗎", timeout: 2},
		{type: "received", message: "如果再驗一次還是一樣", timeout: 3},
		{type: "received", message: "我明天帶你去看醫生", timeout: 3},
		{type: "received", message: "不管結果怎樣你不要想太多", timeout: 2},
		{type: "received", message: "有我在", timeout: 4},
		{type: "read", message: "好😭我再驗一次好了", timeout: 5},
		{type: "received", message: "嗯嗯我先上課", timeout: 4},
		{type: "received", message: "看怎樣再跟我說", timeout: 2},
		],
		auto_render: {
			scene: 2006,
			timeout: 3,
		},
	},
	2003: {
		description: "在廁所-line",
		background: bg_bathroom, 
		line: [
		{type: "sent", message: "欸欸 在嗎?", timeout: 0},
		{type: "sent", message: "發生一件嚴重的事", timeout: 3},
		{type: "sent", message: "我....我好像懷孕了", timeout: 5},
		{type: "sent", message: "我原本月經都很準的", timeout: 8},
		{type: "sent", message: "但這次一直沒有來", timeout: 3},
		{type: "sent", message: "所以買了驗孕棒試試看", timeout: 4},
		{type: "sent", message: "沒想到真的中了", timeout: 3},
		{type: "sent", message: "是兩條線😭", timeout: 2},
		{type: "sent", message: "怎麼辦啦😭", timeout: 2},
		],
		btn_middle: {
			text: "傳送訊息",
			scene: 2004,
		},
		btn_right: {
			text: "撥打電話",
			scene: 2005,
		},
	},
	2004: {
		description: "在廁所-line",
		background: bg_bathroom, 
		line: [
		{type: "sent", message: "欸欸 在嗎?"},
		{type: "sent", message: "發生一件嚴重的事"},
		{type: "sent", message: "我....我好像懷孕了"},
		{type: "sent", message: "我原本月經都很準的"},
		{type: "sent", message: "但這次一直沒有來"},
		{type: "sent", message: "所以買了驗孕棒試試看"},
		{type: "sent", message: "沒想到真的中了"},
		{type: "sent", message: "是兩條線😭"},
		{type: "sent", message: "怎麼辦啦😭"},
		{type: "sent", img: "./img/2/05.png", timeout: 1},
		{type: "sent", message: "你在幹嘛啦 怎麼一直不已讀", timeout:3},
		{type: "read-above", timeout: 3},
		{type: "received", message: "抱歉 我在補習", timeout: 5},
		{type: "received", message: "真的假的", timeout: 5},
		{type: "read", message: "我會拿這種事開玩笑嗎？", timeout: 3},
		{type: "received", message: "不是啦 我是嚇到了", timeout: 4},
		{type: "received", message: "你只驗了一次嗎", timeout: 4},
		{type: "read", message: "恩", timeout: 3},
		{type: "received", message: "你要不要再驗一次啊", timeout: 5},
		{type: "received", message: "不是說有些不太準嗎", timeout: 4},
		{type: "received", message: "如果再驗一次還是一樣", timeout: 3},
		{type: "received", message: "我明天帶你去看醫生", timeout: 3},
		{type: "received", message: "不管結果怎樣你不要想太多", timeout: 5},
		{type: "received", message: "有我在", timeout: 2},
		{type: "read", message: "好😭我再驗一次好了", timeout: 3},
		{type: "received", message: "嗯嗯我先上課", timeout: 2},
		{type: "received", message: "看怎樣再跟我說", timeout: 3},
		],
		auto_render: {
			scene: 2006,
			timeout: 3,
		},
	},
	2005: {
		description: "在廁所-line",
		background: bg_bathroom, 
		line: [
		{type: "sent", message: "欸欸 在嗎?"},
		{type: "sent", message: "發生一件嚴重的事"},
		{type: "sent", message: "我....我好像懷孕了"},
		{type: "sent", message: "我原本月經都很準的"},
		{type: "sent", message: "但這次一直沒有來"},
		{type: "sent", message: "所以買了驗孕棒試試看"},
		{type: "sent", message: "沒想到真的中了"},
		{type: "sent", message: "是兩條線😭"},
		{type: "sent", message: "怎麼辦啦😭"},
		{type: "outgoing dialing", timeout: 1},
		{type: "incoming cancelled", timeout: 5},
		{type: "read-above", timeout: 3},
		{type: "received", message: "我在補習", timeout: 5},
		{type: "received", message: "真的假的", timeout: 5},
		{type: "read", message: "我會拿這種事開玩笑嗎？", timeout: 3},
		{type: "received", message: "不是啦 我是嚇到了", timeout: 4},
		{type: "received", message: "你只驗了一次嗎", timeout: 4},
		{type: "received", message: "你要不要再驗一次啊", timeout: 5},
		{type: "received", message: "不是說有些不太準嗎", timeout: 4},
		{type: "received", message: "如果再驗一次還是一樣", timeout: 3},
		{type: "received", message: "我明天帶你去看醫生", timeout: 3},
		{type: "received", message: "不管結果怎樣你不要想太多", timeout: 5},
		{type: "received", message: "有我在", timeout: 2},
		{type: "read", message: "好😭我再驗一次好了", timeout: 3},
		{type: "received", message: "嗯嗯我先上課", timeout: 2},
		{type: "received", message: "看怎樣再跟我說", timeout: 3},
		],
		auto_render: {
			scene: 2006,
			timeout: 3,
		},
	},
	2006 : {
		description: "再驗一次-訊息後",
		story: [
		"我拿出另一支驗孕棒，再驗一次。",
		"沒有意外還是兩條線，我真的懷孕了。",
		],
		image_story: [
		{url: "./img/2/03.png"},
		{url: "./img/2/04.png", timeout: 2, transition: 3}
		],
		btn_left: {
			text: "繼續",
			scene: 3001,
		},
	},
	2007 : {
		description: "再驗一次-訊息前",
		story: [
		"我拿出另一支驗孕棒，再驗一次。",
		"沒有意外還是兩條線，我真的懷孕了。",
		],
		image_story: [
		{url: "./img/2/03.png"},
		{url: "./img/2/04.png", timeout: 2, transition: 3}
		],
		btn_left: {
			text: "直接打電話給男友",
			scene: 2008,
		},
		btn_middle: {
			text: "傳Line給男友",
			scene: 2009,
		},
	},
	2008: {
		description: "在廁所-再驗一次後-打電話",
		background: bg_bathroom, 
		line: [
		{type: "outgoing dialing", timeout: 1},
		{type: "incoming cancelled", timeout: 5},
		{type: "received", message: "怎麼了我在補習", timeout: 5},
		{type: "read", message: "我發生一件嚴重的事", timeout: 5},
		{type: "received", message: "怎", timeout: 5},
		{type: "read", message: "我....我好像懷孕了", timeout: 3},
		{type: "received", message: "...", timeout: 2},
		{type: "received", message: "真的假的", timeout: 5},
		{type: "read", message: "我會拿這種事開玩笑嗎？", timeout: 3},
		{type: "sent", img: "./img/2/05.png", timeout: 2},
		{type: "received", message: "不是啦 我是嚇到了", timeout: 4},
		{type: "received", message: "你只驗了一次嗎", timeout: 4},
		{type: "read", message: "沒有我驗兩次了", timeout: 3},
		{type: "received", message: "...", timeout: 3},
		{type: "received", message: "本來想說會不會不太準", timeout: 4},
		{type: "received", message: "但既然你已經驗兩次了", timeout: 3},
		{type: "received", message: "沒關係 我明天帶你去看醫生", timeout: 3},
		{type: "received", message: "不管結果怎樣你不要想太多", timeout: 5},
		{type: "received", message: "有我在", timeout: 2},
		{type: "read", message: "好😭", timeout: 3},
		{type: "received", message: "嗯嗯我先上課", timeout: 2},
		{type: "received", message: "看怎樣再跟我說", timeout: 3},
		],
		btn_left: {
			text: "繼續",
			scene: 3001,
		},
	},
	2009: {
		description: "在廁所-再驗一次後-line",
		background: bg_bathroom, 
		line: [
		{type: "sent", message: "欸欸 在嗎?", timeout: 3},
		{type: "sent", message: "發生一件嚴重的事", timeout: 4},
		{type: "sent", message: "我....我好像懷孕了", timeout: 4},
		{type: "sent", message: "我原本月經都很準的", timeout: 3},
		{type: "sent", message: "但這次一直沒有來", timeout: 3},
		{type: "sent", message: "所以買了驗孕棒試試看", timeout: 4},
		{type: "sent", message: "沒想到真的中了", timeout: 3},
		{type: "sent", message: "是兩條線😭", timeout: 3},
		{type: "sent", message: "怎麼辦啦😭", timeout: 3},
		],
		btn_middle: {
			text: "傳送訊息",
			scene: 2010,
		},
		btn_right: {
			text: "撥打電話",
			scene: 2011,
		},
	},
	2010: {
		description: "在廁所-再驗一次後-line",
		background: bg_bathroom, 
		line: [
		{type: "sent", message: "欸欸 在嗎?"},
		{type: "sent", message: "發生一件嚴重的事"},
		{type: "sent", message: "我....我好像懷孕了"},
		{type: "sent", message: "我原本月經都很準的"},
		{type: "sent", message: "但這次一直沒有來"},
		{type: "sent", message: "所以買了驗孕棒試試看"},
		{type: "sent", message: "沒想到真的中了"},
		{type: "sent", message: "是兩條線😭"},
		{type: "sent", message: "怎麼辦啦😭"},
		{type: "sent", img: ["./img/2/05.png", "./img/2/06.png"], timeout: 1},
		{type: "read-above", timeout: 3},
		{type: "received", message: "抱歉 我在補習", timeout: 5},
		{type: "received", message: "真的假的", timeout: 5},
		{type: "read", message: "我會拿這種事開玩笑嗎？", timeout: 3},
		{type: "received", message: "不是啦 我是嚇到了", timeout: 4},
		{type: "received", message: "你只驗了一次嗎", timeout: 4},
		{type: "received", message: "你要不要再驗一次啊", timeout: 5},
		{type: "received", message: "不是說有些不太準嗎", timeout: 4},
		{type: "received", message: "如果再驗一次還是一樣", timeout: 3},
		{type: "received", message: "我明天帶你去看醫生", timeout: 3},
		{type: "received", message: "不管結果怎樣你不要想太多", timeout: 5},
		{type: "received", message: "有我在", timeout: 2},
		{type: "read", message: "好😭我再驗一次好了", timeout: 3},
		{type: "received", message: "嗯嗯我先上課", timeout: 2},
		{type: "received", message: "看怎樣再跟我說", timeout: 3},
		],
		btn_left: {
			text: "繼續",
			scene: 3001,
		},
	},
	2011: {
		description: "在廁所-再驗一次後-line",
		background: bg_bathroom, 
		line: [
		{type: "sent", message: "欸欸 在嗎?"},
		{type: "sent", message: "發生一件嚴重的事"},
		{type: "sent", message: "我....我好像懷孕了"},
		{type: "sent", message: "我原本月經都很準的"},
		{type: "sent", message: "但這次一直沒有來"},
		{type: "sent", message: "所以買了驗孕棒試試看"},
		{type: "sent", message: "沒想到真的中了"},
		{type: "sent", message: "是兩條線😭"},
		{type: "sent", message: "怎麼辦啦😭"},
		{type: "outgoing dialing", timeout: 1},
		{type: "incoming cancelled", timeout: 5},
		{type: "read-above", timeout: 3},
		{type: "received", message: "我在補習", timeout: 5},
		{type: "received", message: "真的假的", timeout: 5},
		{type: "read", message: "我會拿這種事開玩笑嗎？", timeout: 3},
		{type: "received", message: "不是啦 我是嚇到了", timeout: 4},
		{type: "received", message: "你只驗了一次嗎", timeout: 4},
		{type: "received", message: "你要不要再驗一次啊", timeout: 5},
		{type: "sent", img: "./img/2/05.png", timeout: 1},
		{type: "sent", img: "./img/2/06.png", timeout: 1},
		{type: "received", message: "不是說有些不太準嗎", timeout: 4},

		{type: "received", message: "喔...你驗兩次了喔", timeout: 5},
		{type: "received", message: "那沒關係 我明天帶你去看醫生", timeout: 3},
		{type: "received", message: "不管結果怎樣你不要想太多", timeout: 5},
		{type: "received", message: "有我在", timeout: 2},
		{type: "read", message: "好😭", timeout: 3},
		{type: "received", message: "嗯嗯我先上課", timeout: 5},
		{type: "received", message: "看怎樣再跟我說", timeout: 3},
		],
		btn_left: {
			text: "繼續",
			scene: 3001,
		},
	},
	3001: {
		description: "在醫院外",
		background: bg_hospital_outside,
		text_color: "#4d4d4d",
		story_date: "2018/10/1",
		page_turn: true,
		story: [
		"今天子曜帶我去看婦產科。",
		"在進去診所之前，他給了我一包口罩，問我要不要戴？",
		"我當下愣住了，不知道他給我口罩的用意是什麼？",
		"「我想你可能會怕遇到認識的人，所以想說你要不要戴口罩。如果你覺得有關係，那我也跟你一起戴，",
		"如果你覺得沒關係，我們就一起不戴。看你啦！」",
		"我都不知道原來他有那麼貼心",
		],
		btn_left: {
			text: "戴上它",
			scene: 4001,
		},
		btn_middle: {
			text: "把它放回包包",
			scene: 4101,
		},
	},
	4001: {
		description: "在醫院內低頭",
		background: bg_hospital_in_on_lower,
		text_color: "#4d4d4d",
		story: ["「噹噹～」掛在門把上的鈴鐺，讓所有等待看診的人，抬頭看了我一眼。",
		"那一刻，我很慶幸我戴上了口罩。我趕緊找個位置坐下。",
		"--",
		"等待看診的期間，我默默觀察周圍的一切。",
		"電視正在報導印尼發生海嘯，死傷慘重。",
		"坐在我對面的女生腹部微微隆起，牽著那個男生的手，臉上滿是笑容。",
		"這時我和一個女生對到眼，隨即避開視線，她和我一樣帶著口罩，坐在另一個角落。",
		"「噹噹～」又有人走進診所，我連忙低下頭，深怕被認出來。",
		"啊對齁我有戴口罩，但我下意識地還是想躲起來。",
		"其實我也害怕，健保卡上會不會留紀錄，絕對不能被爸媽發現。",
		"昨天晚上我根本睡不著，我不斷在想我怎麼會懷孕？我該怎麼辦？",
		"我不知道這件事被爸媽或是老師同學知道後，他們會怎麼看我？",
		"一想到父母對我失望的表情，甚至同學們在背後指指點點，卻在我面前裝沒事。",
		"想到就很無力",
		],
		btn_left: {
			text: "繼續",
 			scene: 4006,
		},
	},
	4101: {
		description: "在醫院內低頭",
		background: bg_hospital_in_off_lower,
		text_color: "#4d4d4d",
		story: [
		"我選擇不戴口罩，來看婦產科又不一定代表我懷孕，而且我為什麼要這麼畏畏縮縮？",
		"我推開診所的門，走了進去。",
		"掛完號後，隨便找了一個位置坐下。",
		"等待看診的期間，我開始與自己對話。",
		"說不緊張是騙人的，因為這關係到我未來的人生。",
		"如果我檢查完真的懷孕了，我該怎麼辦？是不是要告訴爸媽？",
		"爸媽一定會很生氣，怎麼辦......",
		"如果檢查完只是虛驚一場，我一定要感謝老天爺再給我一個機會",
		"我一定會更加小心！",
		],
		btn_left: {
			text: "繼續",
 			scene: 4104,
		},
	},
	4104: {
		description: "在醫院-叫號",
		background: bg_hospital_in_off_raise,
		text_color: "#4d4d4d",
		story: [
		"12號 方芷潔  進來看診囉！",
		"終於輪到我了。",
		],
		btn_left: {
			text: "繼續",
 			scene: 5001,
		},
	},
	4006: {
		description: "在醫院-叫號",
		background: bg_hospital_in_on_raise,
		text_color: "#4d4d4d",
		story: [
		"12號 方芷潔  進來看診囉！",
		"護士竟然叫了我的全名，我趕緊看看周圍有沒有認識我的人?",
		"一般看醫生都會叫全名嗎？我今天才注意到這件事，感到很不舒服。",
		],
		btn_left: {
			text: "繼續",
 			scene: 5001,
		},
	},
	5001: {
		description: "在醫院-看醫生",
		background: bg_hospital_in_doctor,
		text_color: "#4d4d4d",
		story: [
		"做完了檢查，醫生用很肯定的語氣說：「已經懷孕五週了」",
		"就像被狠狠打了一巴掌，我和子曜傻住了。",
		"看到我們表情凝重，不用等我們開口，醫生就說：「看你們年\
		紀還小，所以先跟你們說一聲。如果想要流掉的話，七週內比較\
		簡單，用吃藥的就可以， 費用也比較低，之後還是要回診檢查。\
		七週以後就要動手術了，費用也比較高。",
		"最重要的是，不管你們之後你們選擇哪一種方式，未滿20歲都是\
		需要家長同意的！",
		],
		btn_left: {
			text: "繼續",
 			scene: 6001,
		},
	},
	6001: {
		description: "在醫院-討論",
		background: bg_hospital_out_discuss,
		text_color: "#4d4d4d",
		story: [
		"「需要家長同意」像是第二個巴掌，讓我和小明久久無法言語。",
		"我不想動手術，手術聽起來就好可怕，這也代表我只剩下兩週的時間可以思考。",
		"事情已經超乎我的想像與控制了，我該怎麼辦？",
		],
		btn_left: {
			text: "繼續",
 			scene: 6002,
		},
	},
	6002: {
		description: "在醫院-討論",
		background: bg_hospital_out_discuss,
		text_color: "#4d4d4d",
		story: [
		"「子曜，我們該怎麼辦？」",
		"「對不起，是我沒有保護好妳」",
		"「當初發生關係都是你請我願的，我們也做好保護措施了，事情發生也不能怪你。」",
		"「但是我們還是學生，根本沒有能力養這個小孩，我們家的經濟情況妳也是知道的」",
		"「嗯，就算我爸媽養得起，他們也不見得會幫我養，可能先打斷我的腿吧？」",
		"「但是不管怎麼樣，還是要先跟父母說吧！不管是要生還是不要生。」",
		"「你說的沒錯，不過我們家很保守，我先探個口風/我...我不敢說」",
		],
		btn_middle: {
			text: "探個口風",
 			scene: 7001,
		},
		btn_right: {
			text: "我不敢說",
 			scene: 7101,
		},
	},
	7001: {
		description: "在家-探個口風",
		background: bg_hospital_out_discuss,
		text_color: "#4d4d4d",
		story: [
		"晚上我和爸媽一起吃飯，看他們心情還可以，我鼓起勇氣開啟了這個話題。",
		"我：我今天在學校阿，聽說隔壁班的一個女生好像懷孕了欸",
		"爸：蛤他不是跟你一樣才幾歲嗎？怎麼那麼年輕就懷孕了",
		"媽：對啊，那她這樣讀書怎麼辦？高中都還沒畢業。",
		"我：ㄜ我不知道誒，就只是聽說。",
		"爸：你現在要做的就是好好讀書，不要跟別人學壞了",
		"媽：對啊～好好讀書，考好大學。",
		"//我：有啦有啦，我有在讀，你們不要再唸了！",
		"//我：只是好奇如果那個人是我，你們會怎麼樣？",
		],
		btn_middle: {
			text: "我有在讀",
 			scene: 8001,
		},
		btn_right: {
			text: "如果是我",
 			scene: 8101,
		},
	},
	8001: {
		description: "在家-如果是我",
		background: bg_hospital_out_discuss,
		text_color: "#4d4d4d",
		story: [
		"我：有啦有啦，只是好奇如果那個人是我，你們會怎麼樣？",
		"爸：這有什麼好奇的，妳不可能會發生這種事。",
		"媽：你怎麼會突然說這個？",
		"我：......",
		"媽：妳是不是懷孕了？",
		"//我：怎麼可能，就說我只是好奇問一下",
		"//我：嗯...我...我懷孕了",
		],
		btn_middle: {
			text: "只是好奇",
 			scene: 8002,
		},
		btn_right: {
			text: "我懷孕了",
 			scene: 8101,
		},
	},
	8101: {
		description: "在家-我有在讀",
		background: bg_hospital_out_discuss,
		text_color: "#4d4d4d",
		story: [
		"我：有啦有啦～我有好好讀書，你們不要再唸了！",
		"媽：妳這什麼態度啊，爸媽多講幾句你就煩了？",
		"爸：你不好好讀書就會像你隔壁班的同學一樣把肚子搞大了",
		"//沈默不語",
		"//不讀書不一定就是壞孩子",
		"//對，我就是把肚子搞大了（接你說什麼？）",
		],
		btn_middle: {
			text: "只是好奇",
 			scene: 8001,
		},
		btn_right: {
			text: "我懷孕了",
 			scene: 8102,
		},
	},
	8102: {
		description: "在家-我有在讀-我懷孕了",
		background: bg_hospital_out_discuss,
		text_color: "#4d4d4d",
		story: [
		"我：嗯...我...我懷孕了",
		"爸：（拍桌）妳說什麼！",
		"媽：你在跟我開玩笑嗎？妳不是都在讀書嗎？",
		"妳怎麼有時間把自己的肚子搞大？",
		"妳是不是騙我們要去圖書館，結果跑去亂搞？",
		"爸：我怎麼會有你這種女兒，臉都被你丟光了！",
		"我：（眼淚滴答滴答滴在餐桌上）",
		"媽：你確定懷孕了嗎？",
		"我：嗯",
		"媽：去看過醫生了嗎？",
		"我：嗯",
		"媽：醫生說什麼？小孩多大了",
		"我：五週了",
		"爸：那個男的是誰，叫他過來我打斷他的腿",
		"我：你在說什麼？！他是我男友欸，我也有責任你不要都怪他",
		"媽：哼才多大就交男朋友，你們知道什麼叫愛嗎？現在都搞出人命了",
		"我：對不起，我不是故意的。",
		"我：難道就你們大人才懂愛嗎？",
		],
		btn_middle: {
			text: "只是好奇",
 			scene: 8001,
		},
		btn_right: {
			text: "我懷孕了",
 			scene: 8101,
		},
	},
};